# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build for RP2350

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Swift
      uses: slashmo/install-swift@v0.4.0
      with:
        version: swift-DEVELOPMENT-SNAPSHOT-2024-04-13-a

    - name: Test Swift Install
      run: swift --version

    - name: Install GCC, GNU Embedded Toolchain for ARM, Ninja
      run: sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential g++ libstdc++-arm-none-eabi-newlib ninja-build
    
    - name: Install Pico SDK
      run: cd ${{github.workspace}}; git clone https://github.com/raspberrypi/pico-sdk.git ; git submodule update --init;

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: export PICO_SDK_PATH=${{github.workspace}}/pico-sdk; export PICO_BOARD=pico2; cmake -B ${{github.workspace}}/build -G Ninja .

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build 

    - name: Release
      uses: softprops/action-gh-release@v2
      with: 
        make_latest: true
        files: ${{github.workspace}}/build/swift-blinky.uf2
          

        



